export class Member {

    memberId :number;
	area : any;
	eligible:string;
	firstName:string;
    middleName:string;
	lastName:string;
	email:string;
	type:string;
	hajeriNo:string;
	baithakLocation:any;
	addharNumber:string;
	education:string;
	add1:string;
	add2:string;
	add3:string;
	add4:string;
	city:string;
	country:string;
	additionalInfo:string;
	division:string;
	dob:string;
	gender:string;
	googleMapLink:string;
	initial:string;
	role:string;
	twoWheeler:boolean;
	fourWheeler:boolean;
	// both:string;
	noVehical:boolean;
	phoneNumber:string;
	// ownBaithakId:string;
	eligibleForNone:boolean;
	eligibleForChild:boolean;
	eligibleForGents:boolean;
	eligibleForLadies:boolean;
	

 marathiRead:boolean;
 marathiSpeak:boolean;
 marathiWrite:boolean;
 englishRead:boolean;
 englishSpeak:boolean;
 englishWrite:boolean;
 hindiRead:boolean;
 hindiSpeak:boolean;
 hindiWrite:boolean;
 longitude:string;
 latitude:string;
 mobile:string;
 occupation:string;
 ownBaithakDay:string;
 panNo:string;
 phone:string;
 photoBase64:string;
 pincode:string;
 state :string;
 status:string;
 twoWheelerDetail:string;
 fourWheelerDetail:string;
 weeklyOffs:any[];
 members:string;
 locations:string;
}
