export class Member {

    memberId :number;
	firstName:string;
    middleName:string;
	lastName:string;
	email:string;
	hajeriNo:string;
	hajeriNoDetails:string;
	addharNumber:string;
	education:string;
	add1:string;
	add2:string;
	add3:string;
	add4:string;
	city:string;
	country:string;
	additionalInfo:string;
	division:string;
	dob:string;
	gender:string;
	googleMapLink:string;
	initial:string;
	roles:string;
	vehiclesType:string;
	phoneNumber:string;
	ownBaithakId:string;
 languagesRead:string;
 languagesSpeak:string;
 languagesWrite:string;
 longitude:string;
 latitude:string;
 mobile:string;
 occupation:string;
 ownBaithakDay:string;
 panNo:string;
 phone:string;
 photoBase64:string;
 pincode:string;
 state :string;
 status:string;
 vehicleDetails:string;
 vehicleType:string;
 weeklyOffs:string;
 members:string;
 locations:string;
}
